/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignRouteImport } from './routes/sign'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SignUpRouteImport } from './routes/sign/up'
import { Route as SignInRouteImport } from './routes/sign/in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => SignRoute,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/in',
  path: '/in',
  getParentRoute: () => SignRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sign': typeof SignRouteWithChildren
  '/sign/in': typeof SignInRoute
  '/sign/up': typeof SignUpRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/sign': typeof SignRouteWithChildren
  '/sign/in': typeof SignInRoute
  '/sign/up': typeof SignUpRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign': typeof SignRouteWithChildren
  '/sign/in': typeof SignInRoute
  '/sign/up': typeof SignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign' | '/sign/in' | '/sign/up' | '/' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign' | '/sign/in' | '/sign/up' | '/' | '/api/auth/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign'
    | '/sign/in'
    | '/sign/up'
    | '/_authenticated/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignRoute: typeof SignRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/sign/up': {
      id: '/sign/up'
      path: '/up'
      fullPath: '/sign/up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof SignRoute
    }
    '/sign/in': {
      id: '/sign/in'
      path: '/in'
      fullPath: '/sign/in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof SignRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SignRouteChildren {
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

const SignRouteChildren: SignRouteChildren = {
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}

const SignRouteWithChildren = SignRoute._addFileChildren(SignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignRoute: SignRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
